# Generated by Django 2.1.3 on 2018-11-20 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False, verbose_name='SSN')),
                ('prefix', models.CharField(choices=[('Dr', 'Dr')], max_length=2)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('specialty', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(help_text='Enter the hospital department: ', max_length=25, null=True, verbose_name='Hospital Dept')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False, verbose_name='SSN')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('drugid', models.IntegerField(null=True, verbose_name='DrugID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.DateField(null=True)),
                ('desc', models.TextField(help_text='Enter the prescription : ', null=True, verbose_name='Prescription')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Doctor')),
                ('drug', models.ForeignKey(help_text='Enter the drug id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Pharmacy')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Patient')),
            ],
            options={
                'ordering': ['patient'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hosp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Hospital'),
        ),
    ]
