# Generated by Django 2.1.4 on 2019-04-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
