# Generated by Django 2.1.3 on 2018-12-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(help_text='Enter the hospital department: ', max_length=25, null=True, verbose_name='Hospital Dept')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('drugid', models.IntegerField(null=True, verbose_name='DrugID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
