# Generated by Django 2.1.4 on 2019-03-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
