# Generated by Django 2.1.4 on 2019-04-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190403_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='pre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Prescription'),
        ),
    ]
