# Generated by Django 2.1.4 on 2019-04-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pharmacist_pre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='pre',
        ),
        migrations.AddField(
            model_name='prescription',
            name='phar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Pharmacist'),
        ),
    ]
