# Generated by Django 2.1.4 on 2019-04-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190403_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='phar',
        ),
    ]
