# Generated by Django 2.1.3 on 2018-12-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181204_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True, unique=True, verbose_name='Email'),
        ),
    ]
