# Generated by Django 2.1.4 on 2018-12-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181214_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='desc',
            field=models.TextField(null=True, verbose_name='Prescription Details'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dop',
            field=models.DateField(null=True, verbose_name='Prescription Date'),
        ),
    ]
