# Generated by Django 2.1.4 on 2018-12-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20181216_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='prefix',
            field=models.CharField(choices=[('Dr', 'Dr')], default='Dr', max_length=2),
        ),
    ]
