# Generated by Django 2.1.4 on 2018-12-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20181216_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='desc',
            field=models.CharField(max_length=150, null=True, verbose_name='Prescription Details'),
        ),
    ]
