# Generated by Django 2.1.4 on 2018-12-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20181217_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-dop']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Hospital'),
        ),
    ]
