# Generated by Django 2.1.4 on 2019-03-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20181217_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(default=123, verbose_name='Phone Number'),
        ),
    ]
